version: '3.8'

services:
  php:
    build: .
    container_name: php-xdebug
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - php
