version: '3.8'

services:
  php:
    build: .
    container_name: php-xdebug
    volumes:
      - .:/var/www/html
    ports:
      - "9003:9003"
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
